### ISSUE TITLE
Error on restart HA using current themes

### ISSUE THREAD

**Issue by jvcsw** [ChristophCaina/home-assistant-theme-outline-edge#5]
# Problem/Motivation

This error appears when restart HA:

The system cannot restart because the configuration is not valid: Error loading /config/configuration.yaml: mapping values are not allowed here in "/config/themes/outline-edge-no-borders.yaml", line 28, column 66

The same with: HomeAssistant-Default.yaml

## Expected behavior

No errors on loading.

## Actual behavior

Impossible load the configuration with current themes.

## Steps to reproduce

Copy yaml files to the themes folder and restart.

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by ChristophCaina** [comment]
Hi, sorry - haven't got any notification that a new issue has been reported :-(

Can you please let me know if the issue is still present?
I've tried to reproduce it but were not able to... restarting of HomeAssistant was working well with every theme I've selected.

**Comment by PacmanForever** [comment]
No problem.

This is the current error with the last version of all:

![imagen](https://user-images.githubusercontent.com/37216513/218103088-0620f821-f989-4666-a416-2726c195880d.png)

**Comment by ChristophCaina** [comment]
Hm... I think I know what the issue is...
Your path seems to be incorrect.
![Screenshot_20230210-151107](https://user-images.githubusercontent.com/26391061/218112692-bf6264ee-1141-4798-8998-348834aee217.png)

Have you installed the Theme via hacs or manually?

**Comment by ChristophCaina** [comment]
Probably i Made a mistake in the readme... 🤔

**Comment by PacmanForever** [comment]
I have installed it manually.
I'm using themes/outline folder with the same issue, configured with "themes: !include_dir_merge_named themes"

I don't know the reason.

**Comment by ChristophCaina** [comment]
OK. I will have a Look into this over the Weekend.
Since i could Not reproduce this Case yet, I need to Check the yaml Code.
It is probably Just a small Thing Like a Space in the wrong place or similar.

Can you please Check one of the other Theme Files as Well?

**Comment by ChristophCaina** [comment]
OK, I removed the theme on my system - and installed it again from HACS... restart is working without any issues.

I've already checked the mentioned line from your error:
Line 27, column 66...

Line 27 only has 55 columns..
![grafik](https://user-images.githubusercontent.com/26391061/218248061-421f43bb-5284-4a57-8711-295566bd70e9.png)


Can you please open the file in notepad and provide a Screenshot of that line?

**Comment by PacmanForever** [comment]
In this file (mentioned before): outline-edge-no-borders.yaml

I have this:

![imagen](https://user-images.githubusercontent.com/37216513/218756016-fd0c3632-fcb7-4aa5-adf4-e21ede7c7977.png)

**Comment by ChristophCaina** [comment]
... I don't know where this is comming from.
What your screenshot is showing - isn't a yaml file - and for sure not part of the theme files I have in the repository.
You can check the source code to check how the file should look like... (or, as shown in my screenshot above... that's how the file should look like)

**Comment by PacmanForever** [comment]
Ooooook!!
I found the problem!

Some issue with the cache. I donwloaded the file again with other browser and now works fine.

Sorry for the inconvenience.

**Comment by ChristophCaina** [comment]
no problem :)
Btw - if you are using HACS, you can just add the repository URL to HACS for an automated installation and updates (another update will probably come soon to add a few more sensor states and small changes with ON / OFF states on other sensors)
